services:
  postgres:
    image: postgres:15-alpine
    container_name: url_shortener_db
    env_file:
      - server/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    command: -c max_connections=250
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: url_shortener_redis
    ports:
      - "6379:6379"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - server/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urlshortener
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      REDIS_URL: redis://redis:6379
      SPRING_REDIS_HOST: redis
    restart: always

volumes:
  postgres_data: