server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 1000

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/urlshortener}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 200
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      url: ${REDIS_URL:}
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile

logging:
  level:
    org.springframework.security: WARN
    com.urlshortener: WARN

app:
  base-url: ${APP_BASE_URL:http://localhost:8080/}
  jwt:
    secret: ${JWT_SECRET:super_secret_key_for_jwt_which_must_be_long_enough_to_be_secure}
    expiration-ms: 3600000
    cookie-name: jwt_token
  admin:
    emails: ${ADMIN_EMAILS:gawhadehimanshu12@gmail.com,rohit010100@gmail.com}
  cookie:
    secure: ${SECURE_COOKIE:false}