name: Keep Render Awake

on:
  schedule:
    - cron: '*/14 0-18 * * *' # Runs every 14 minutes from 5:30 AM to 12:30 AM IST (0-18 UTC)
  workflow_dispatch: # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Application
        run: |
          curl -s -f https://easyurl.tech/ || echo "Ping failed, but workflow continues."
